OLID_PATH = './OLIDv1.0'
GERMEVAL_PATH = './GermEval2018'
PERSIAN_PATH  = './Persian'
SAVE_PATH = './save'

LABEL_DICT_OLID = dict()
LABEL_DICT_GERMEVAL = dict()
LABEL_DICT_EN_DE = dict()
LABEL_DICT_FA = dict()

ID_LABEL = 'id'
TWEET_LABEL = 'tweet'

TASK_PREFIX = 'subtask_'
TASK_A_LABEL = TASK_PREFIX + 'a'
TASK_B_LABEL = TASK_PREFIX + 'b'
TASK_C_LABEL = TASK_PREFIX + 'c'